### PR TITLE
M ltoolkit

### PR DESCRIPTION
**Pull request by Atharva-Thakur**
1. Added MLtoolkit functionality.

### CODE REVIEW

**Comment by Atharva-Thakur** [comment]
> * the sa

please make the 3rd point clear.

**Comment by Atharva-Thakur** [comment]
Please review the latest code e5d5423

**Comment by Atharva-Thakur** [comment]
Some penalty don't work in certain scenarios
https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

**Comment by Shrutisd1003** [comment]
> > * the sa
> 
> please make the 3rd point clear.

For regressor, let the user choose the target variable from a list that has columns containing only numeric data and similarly for classifiers the list should have columns with non-numeric data.
And secondly for the the input parameter list for any model, the list should contain columns that can be allowed (numeric and not null).

**Comment by Shrutisd1003** [comment]
> Please review the latest code [e5d5423](https://github.com/Atharva-Thakur/Insights/commit/e5d54238771773482fc96f4850b3314322c77855)

Good work :)

**Comment by Shrutisd1003** [comment]
> Some penalty don't work in certain scenarios https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

Yes I faced the problem initially
What I was thinking is we can add a little info so that the user can have at least some idea of what columns or parameters he/she can choose.

We need to brainstorm this first :)

**Comment by Shrutisd1003** [comment]
Screenshot 2024-04-20 144138


image


KNN regressor model (or any regressor model) does not take or predict categorical data, so what I am saying we do not display variables that the model is not compatible with in the first place instead of giving an error.

**Pull request merged**
